auth questions
`gcp.delete_this_vm()` fails. Maybe it needs an updated `~/.cloud.json` file configured for the `fireworks` username instead of `sisyphus`.

```
ERROR: (gcloud.compute.instances.delete) Could not fetch resource:
 - Insufficient Permission: Request had insufficient authentication scopes.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fireworker/borealis/cloud/gcp.py", line 73, in delete_this_vm
    fp.run_cmd(['gcloud', '--quiet', 'compute', 'instances', 'delete',
  File "/home/fireworker/borealis/util/filepath.py", line 49, in run_cmd
    out = subprocess.run(
  File "/home/fireworker/.pyenv/versions/3.8.1/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gcloud', '--quiet', 'compute', 'instances', 'delete', 'jhm-0', '--zone', 'us-west1-b']' returned non-zero exit status 1.
```